name: Terraform Deploy

on:
  push:
    branches:
      - main
      - feature/expansion-alb-cf-ci  # ←今のブランチ名（なければ main だけでOK）

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
